
## Selecting a method

### Estimating the biomass of a biome

There is no single method for estimating biomass stocks, but a number of methods depending on the scale considered [@gibbs07]. On a national or larger scale, mean values per biome are usually employed [@fao06]: the amount of biomass is estimated by multiplying the surface area of each biome by the mean amount of biomass per unit surface area of this biome. And mean amounts per biome are estimated from measurements made on a smaller scale. Biomass on national to landscape scales can be estimated by remote sensing. Regardless of whether this uses satellite-borne optical sensors (Landsat, MODIS), high resolution satellite images (Ikonos, QuickBird), low resolution aerial photographs, satellite-borne radar or microwave sensors (ERS, JERS, Envisat, PALSAR), or laser sensors (Lidar), all these methods assume that field measurements are available to adjust biomass-predicting models to remote sensing observations. When dealing with satellite-borne optical sensors, field data are necessary to calibrate the relationship between biomass and satellite vegetation indices (NDVI, NDFI, AVI, GVI, etc.) [@dong03; @saatchi07]. High-resolution images and aerial photographs provide information on tree crown size and height, and field data are then necessary to relate this information to biomass [for example @bradley88; @holmgren94; @stonge08; @gonzalez10]. The same applies to Lidar information on the vertical structure of forests, and to radar and microwave information on the vertical distribution of plant water [for example @lefsky02; @patenaude04]. But remote sensing-based methods have their limitations in terms of providing precise biomass measurements (particularly surface areas) and differentiating forest types due to the technical, financial and human resources available. They are also hindered by cloud cover and are susceptible to saturated signals for certain vegetation types.

Therefore, biomass estimation methods on a landscape or greater scale rely on field measurements taken between the landscape and plot scales. Biomass estimations on this scale are based on forest inventory data: inventory of a sample of trees if the area is large, or otherwise a full inventory (particularly in permanent plots of a few hectares). On a smaller scale, individual biomass measurements may be taken by weighing trees and understorey vegetation.


### Estimating the biomass of a forest or a set of forests

Estimations of forest biomass or nutrient content based on forest inventories require:

1. an exhaustive or statistical inventory of the trees growing;
2. models to evaluate carbon stocks from the dimensions of the individuals measured;
3. an evaluation of the biomass contained in the necromass (standing dead wood) and in understorey vegetation.

In this guide we focus on the second aspect even though an inventory and quantitative evaluation of the understorey is not necessarily easy to obtain, particularly in highly mixed forests.

Two main methods based on inventory data may be employed to estimate tree carbon or mineral element stocks [@macdicken97; @hairiah01; @AGO02; @ponce04; @monreal05; @pearson05; @dietz11]:
(1) use of biomass/nutrient content tables: this solution is often adopted as it rapidly yields the carbon or nutrient content of a plot at a given time point. In general, all the different (above-ground, below-ground, ground litter, etc.) compartments of the ecosystem are considered. Trees are specifically felled for these operations. The compartments (cross cuts) may vary depending on application and the field of interest (see chapter \@ref(ter)). (2) Use of models to estimate successively tree volume, wood density and nutrient content. This method has the advantage of dissociating the different components, making it possible to analyze the effect of age and growing conditions independently on one or another of the components. In general, only the trunk can be modeled in detail (between and within rings). The biomass of the other compartments is estimated from volume expansion factors, mean wood density measurements and nutrient concentration. In all cases these models call upon one and the same model type that indifferently groups together "volume tables, biomass tables, nutrient content tables, etc." and which is described here in this guide.

Biomass and nutrient content tables are closely related to volume tables that have been the subject of much study for nearly two centuries. The first tables were published by @cotta04 [*in* @bouchon74] for beech (*Fagus sylvatica*). The principle employed is to link a variable that is difficult to measure (e.g. the volume of a tree, its mass, or its mineral elements content) to variables that are easier to determine, e.g. tree diameter at breast height (DBH) or height. If both characteristics are used, we speak of a double-entry table; if only DBH is used, we speak of a single-entry table. In general, close correlations are obtained and the polynomial, logarithmic and power functions are those most widely used. For more details, readers may see the reviews by @bouchon74; @hitchcock79; @parde80; @cailliez80; @parde88, and more recently by @parresol99; @parresol01.

These functions are relatively simple but have three major snags. First, they are not particularly generic: if we change species or stray outside the calibration range, the equations must be used with caution. The chapter on sampling gives a few pointers on how to mitigate this problem. The key principle is to cover as best as possible the variability of the quantities studied.

The second snag with these functions lies in the very nature of the data processed (volumes, masses, nutrient content). In particular, problems of heteroscedasticity may arise (i.e. non homogeneous variance in biomasses in relation to the regressor). This has little impact on the value of the estimated parameters: the greater the number of trees sampled, the more rapid the convergence toward real parameter values [@kelly87]. But everything concerning the confidence interval of the estimations is affected:

1. the variance of the estimated parameters is not minimal;
2. this variance is biased; and 
3. residual variance is poorly estimated [@cunia64; @parresol93; @gregoire89].

If no efforts are made to correct these heteroscedasticity problems, this has little impact on the mean biomass or volume values estimated. By contrast, these corrections are indispensable if we are to obtain correct confidence intervals around these predictions. Two methods are often put forward to correct these heteroscedasticity problems: the first consists in weighting (for instance by the inverse of the diameter or the squared diameter), but here everything depends on the weighting function and in particular on the power applied. The second consists in taking the logarithm of the terms in the equation, but here the simulated values need to be corrected to ensure that the estimated values return to a normal distribution [@duan83; @taylor86]. Also, it may well happen that the log transformation does not result in a linear model [@navar02; @saintandre05].

The third snag is due to the additivity of the equations. Biomass measurements, then the fitting of functions, are often made compartment by compartment. The relations are not immediately additive, and a desired property of the equations system is that the sum of the biomass predictions made compartment by compartment equals the total biomass predicted for the tree [see @kozak70; @reed85; @navar02]. Three solutions are in general suggested [@parresol99]:

- total biomass is calculated by summing the compartment by compartment biomasses, and the variance of this estimation uses the variances calculated for each compartment and the covariances calculated two by two;

- additivity is ensured by using the same regressors and the same weights for all the functions, with the parameters of the total biomass function being the sum of the parameters obtained for each compartment;

- the models are different compartment by compartment but are fitted jointly, and additivity is obtained by constraints on the parameters.

Each method has its advantages and disadvantages. Here in this guide we will fit a model for each compartment and a model for total biomass, while checking that additivity is respected. Concrete examples (dubbed "red lines") will be used throughout this guide as illustrations. These are based on datasets obtained during studies conducted in a natural wet tropical forest in Ghana [@henry10].

### Measuring the biomass of a tree

Biomass tables create a link between actual individual biomass measurements and biomass estimations in the field based on inventory data. Weighing trees to measure their biomass is therefore an integral part of the approach used to construct allometric equations, and a large part of this guide is therefore devoted to describing this operation. Although the general principles described in chapter \@ref(ter) (tree segmentation into compartments of homogenous dry weight density, measurement of dry matter / fresh volume ratios in aliquots, and application of a simple rule of three) should yield a biomass estimation for any type of woody plant, this guide will not address all the special cases. Plants that are not trees but potentially have the stature of trees (bamboo, rattan, palms, tree ferns, Musaceae, *Pandanus spp.*, etc.) are considered as exceptions.

Plants that use trees as supports for their growth (epiphytes, parasitic plants, climbers, etc.) are another special case [@putz83; @gerwing00; @gerwing06; @gehring04; @schnitzer06; @schnitzer08]. Their biomass should be dissociated from that of their host.

Finally, hollow trees, and trees whose trunks are shaped very differently from a cylinder (e.g. *Swartzia polyphylla* DC.), strangler fig, etc., are all exceptions to which biomass tables cannot be applied without specific adjustments [@nogueira06].
