
## Sampling to construct volume tables

As a first step, let us consider the problem of predicting the volume or biomass of a particular tree using volume or biomass tables. How many trees need to be measured to construct the tables (\S\ \@ref(size))? Which trees in the stand should be selected for measurement? This second question begs another: how should we sort the trees in the sample in relation to volume table entry variables, starting with the tree size (\S\ \@ref(vent))? How, if necessary, should we stratify the sample (\S\ \@ref(stratif))? Is it best to select individuals far apart in the forest, or on the contrary inventory all the trees in a given plot (\S\ \@ref(sel))?


### Number of trees {#size}

Given the limitations of the sampling theory, the number of measured trees for volume or biomass (in other terms, the sample size) is generally selected empirically, based on rules established by experience. A general principle is that, for any given precision, the more variable the material, the larger the sample size: smaller sample sizes are required for a plantation of clones than for a natural tropical forest, for a given species than for a group of species, for a 10 ha plot than for a natural area. In certain cases, such as for root biomass, it is the cost of the measurements that determines the sample size rather than the desired precision of the predictions: the number of trees selected corresponds to an acceptable amount of work to obtain the measurements. As a rough guide, when constructing volume tables, the Forester's Memento [p.256 @ctft89] recommends measuring about 100 trees "for one or more stands of recent plantation over a small surface area (e.g. silviculture research plots)". [p.108 @parde88] recommended the sample sizes given in Table \@ref(tab:eff), that depend on the surface area of the zone in which the volume tables are to be used. Different volume and biomass tables have been compiled by @zianis05 for Europe and by @henry11 for sub-Saharan Africa. The sample sizes reported for the volume and biomass tables listed in these literature reviews give some idea of the sampling effort required. @chave04 showed that when 300 trees were used to construct a biomass table, the resulting biomass estimation for a wet tropical stand (Barro Colorado Island in Panama) had a coefficient of variation of barely 3.1\ \%. This coefficient of variation rose above 10\ \% when the number of trees used to construct the biomass table fell below 50, with the coefficient of variation increasing approximately in proportion to $1/\sqrt{n}$ [Figure 3 @chave04]. @vanbreugel11 noted the same type of decrease in estimation precision with the sample size used to construct the biomass table, for $n$ between 49 and 195 trees.

```{r eff}

kab <- tibble(
  area = c(
    "Single, homogeneous stand",
    "15-ha plot",
    "1000-ha forest",
    "Natural area",
    "Species area"
    ),
  n = c("30", "100", "400", "800", "2000 to 3000")
  )

kab_opt <- list(
  x = kab,
  caption = "(ref:eff)",
  caption.short = "Number of trees to be measured to establish a volume table for different surface areas over which the tables are to be used",
  col.names = c("Area", cell_spec("n", italic = TRUE)),
  escape = F
)

display_table()

```


The costlier an observation, in terms of measurement time and effort, the more the sampling plan tends to be determined by the sampling effort that workers are willing to make rather than by the desired precision of the estimation. As the above-ground biomass of a tree is more difficult to measure than the volume of its stem, biomass tables tend to be constructed using fewer observations than volume tables. Certain biomass tables are constructed from measurements in only a few trees [8 trees for @brown95 in Brazil, 12 trees for @ebuy11 in the Democratic Republic of Congo, 14 trees for @deans96, 15 trees for @russell83 in Brazil].
Root tables, that require an even greater measurement effort, are often based on even smaller sample sizes. Tables constructed using such small samples are generally unreliable, and in any case are valid only very locally. However, these small datasets can subsequently be grouped together into more impressive datasets that have advantages for model fitting (on condition that the variability induced by the merging of these datasets can be controlled by effect covariables: age, wood density, etc. or by stratification factors: species, type of vegetal formation\ldots).


