

# In the field {#ter}

The field step is the most crucial as it may generate measurement errors that cannot be corrected. This phase must be governed by three key principles: (*i*) it is better to weigh everything in the field rather than calculate a volume and multiply it later by a density measurement (see chapter \@ref(biol) and variations in stem shape and wood density); (*ii*) if wood aliquots are taken, it is best to weigh the whole then the aliquot to follow moisture loss; finally (*iii*) as a biomass campaign requires a great deal of work and is very costly to undertake, other measurements may be taken at the same time to avoid a subsequent return to the field (e.g. stem profile, sampling for nutrient content).

Selecting trees to be measured in the field (see chapter \@ref(samp)), whether as individuals or exhaustively over a given area, means that the trees must be marked with paint, measured for circumference if possible at breast height (by circling the trunk with paint at this point) and measured for height. This procedure is used to check that the tree selected indeed corresponds to the sampling plan chosen (case of a selection by individual) and provides for control measures once the tree has been felled. It is also very practical to take a photo of the individual selected and draw a schematic diagram of the tree on the field form. This makes it easier to interpret the data and check the results obtained. In general, trees that are too unusual (crown broken, stem knotty or sinuous) should not be selected unless these stems account for a significant proportion of the stand, or if the aim is to quantify an accident (e.g. crown breaking subsequent to frost). Likewise, trees located in an unrepresentative environment should be excluded (forest edge, clearing, degraded forest, etc.) as their architecture often differs from the other trees in the stand. Finally, field constraints (slope, access, stand non compliant with the stratum, etc.) may well call the original sampling into question.

The general basis for measuring biomass, and even more nutrient content, is the rule of three between fresh biomass measured in the field, fresh biomass of the aliquot, and oven-dried biomass of the aliquot. As the different organs of a tree do not have the same moisture content or the same density, it is preferable to proceed by compartmentalization to take account of variations in tree density and moisture content (and nutrient concentrations when calculating nutrient content). The finer the stratification, the more precise the biomass estimation, but this requires a great deal more work. A compromise must therefore be found between measurement precision and work rate in the field. Conventionally, a tree is divided into the following compartments: the trunk, distinguishing the wood from the bark, and that should be sawed into logs to determine variations in density and moisture content in relation to section diameter; branches that are generally sampled by diameter class, distinguishing or not the wood from the bark; the smallest twigs, generally including buds; leaves; fruits; flowers; and finally roots by diameter class. An example of a such a compartmentalization is given in Figure \@ref(fig:compart) for beech.


```{r compart2, dev='tikz', cache=TRUE, fig.process = pdf2png, out.width="100%", fig.cap="Example of tree compartmentalization for a biomass and nutrient content campaign on beech in France."}

grid.arrange(grImport::pictureGrob(comparts_vec), ncol = 2)
grid.text(label = "Leaves: total weight and sample taken for", 
          x = 0.4, y = 0.8, just = 0
          )
grid.text(label = "moisture content", 
          x = 0.4, y = 0.76, just = 0
          )
grid.text(label = 'Branches (cross cuts $\\varnothing\\geq$ 20 cm; 20 cm $>\\varnothing\\geq$ 7 cm;',
          x = 0.37, y = 0.55, just = 0
          )
grid.text(label = bquote("7 cm  $>\\varnothing\\geq$ 4 cm; 4 cm $>\\varnothing$): weighed and sample taken of"),
          x = 0.37, y = 0.51, just = 0
          )
grid.text(label = "cross cuts for moisture content",
          x = 0.37, y = 0.47, just = 0
          )
grid.text(label = "Trunk (wood and bark): logs weighed and disks cut every 2 m",
          x = 0.32, y = 0.35, just = 0
          )
grid.text(label = "for moisture content and wood/bark proportion",
          x = 0.32, y = 0.31, just = 0
          )
grid.text(label = "Roots (cross cuts $\\varnothing\\geq$ 10 mm; 10 mm $>\\varnothing\\geq$ 2 mm;",
          x = 0.38, y = 0.2, just = 0
          )
grid.text(label = "2 mm $>\\varnothing$): weighed and sample taken by",
          x = 0.48, y = 0.16, just = 0
          )
grid.text(label = "cross-cutting for moisture content",
          x = 0.48, y = 0.12, just = 0
          )

```






