

## Predicting the volume or biomass of a stand

If we want to predict the volume or biomass of a stand using biomass tables, we cannot measure model entries for all the trees in the stand, only for a sample. The volume or biomass of the trees in this sample will be calculated using the model, then extrapolated to the entire stand. Predicting the volume or biomass of a stand therefore includes two sources of variability: one related to the model's individual prediction, the other to the sampling of the trees in the stand. If we rigorously take account of these two sources of variability when making predictions on a stand scale, this will cause complex double sampling problems as mentioned in sections \@ref(peup) and \@ref(sampeup) [@parresol99].

The problem is slightly less complex when the sample of trees used to construct the model is independent of the sample of trees in which the entries were measured. In this case we can consider that the prediction error stemming from the model is independent of the sampling error. Let us assume that $n$ sampling plots of unit area $A$ were selected in a stand whose total area is $\mathcal{A}$. Let $N_i$ be the number of trees found in the $i$th plot ($i=1,\ \ldots,\ n$) and let $X_{ij1},\ \ldots,\ X_{ijp}$ be the $p$ effect variables measured on the $j$th tree of the $i$th plot ($j=1,\ \ldots,\ N_i$). @cunia65; @cunia87c considered the particular case where biomass is predicted by multiple regression based on the $p$ effect variables. The estimation of stand biomass is in this case:

\begin{eqnarray*}
\hat{B} &=&
\frac{\mathcal{A}}{n}\sum_{i=1}^n\frac{1}{A}\sum_{j=1}^{N_i}
(\hat{a}_0+\hat{a}_1X_{ij1}+\ldots+\hat{a}_pX_{ijp})
\\ &=& \hat{a}_0\Big(\frac{\mathcal{A}}{nA}\sum_{i=1}^nN_i\Big)
+\hat{a}_1\Big(\frac{\mathcal{A}}{nA}\sum_{i=1}^n\sum_{j=1}^{N_i}X_{ij1}\Big)
+\ldots+\hat{a}_p\Big(\frac{\mathcal{A}}{nA}\sum_{i=1}^n\sum_{j=1}^{N_i}X_{ijp}\Big)
\end{eqnarray*}

where $\hat{a}_0,\ \ldots,\ \hat{a}_p$ are the estimated coefficients of the regression. If $X^{\star}_0=(\mathcal{A}/nA)\sum_{i=1}^nN_i$ and for each $k=1,\ \ldots,\ p$,
\[
X^{\star}_k=\frac{\mathcal{A}}{nA}\sum_{i=1}^n\sum_{j=1}^{N_i}X_{ijk}
\]
The estimated biomass of the stand is therefore
\[
\hat{B}=\hat{a}_0X^{\star}_0+\hat{a}_1X^{\star}_1+\ldots+\hat{a}_pX^{\star}_p
\]
Interestingly, the variability of $\hat{\mathbf{a}}={}^{\mathrm{t}}[\hat{a}_0,\ \ldots,\ \hat{a}_p]$ depends entirely on model fitting, not on stand sampling, while on the other hand, the variability of  $\mathbf{x}={}^{\mathrm{t}}[X^{\star}_0,\ \ldots,\ X^{\star}_p]$ depends entirely on the sampling, not on the model. Given that these two errors are independent,
\[
\mathrm{E}(\hat{B})=\mathrm{E}({}^{\mathrm{t}}{\hat{\mathbf{a}}}\mathbf{x})={}^{\mathrm{t}}{\mathrm{E}(\hat{\mathbf{a}})}\ \mathrm{E}(\mathbf{x})
\]
and
\[
\mathrm{Var}(\hat{B})={}^{\mathrm{t}}{\mathbf{a}}\boldsymbol{\Sigma}_{\mathbf{x}}
\mathbf{a}+{}^{\mathrm{t}}{\mathbf{x}}\boldsymbol{\Sigma}_{\mathbf{a}}\mathbf{x}
\]
where $\boldsymbol{\Sigma}_{\mathbf{a}}$ is the $(p+1)\times(p+1)$ variance-covariance matrix of the model's coefficients while $\boldsymbol{\Sigma}_{\mathbf{x}}$ is the $(p+1)\times(p+1)$ variance-covariance matrix of the sample of $\mathbf{x}$. The first matrix is derived from model fitting whereas the second is derived from stand sampling. Thus, the error for the biomass prediction of a stand is the sum of these two terms, one of which is related to the prediction error of the model and the other to stand sampling error.

More generally, the principle is exactly the same as when we considered `r ifelse(book_format == "latex", "on page \\pageref{errmes}", "in section \\@ref(errmes)")`, an uncertainty related to the measurement of the effect variables $X_1,\ \ldots,\ X_p$. A measurement error is not of the same nature as a sampling error. But from a mathematical standpoint, the calculations are the same: in both cases this means considering that the effect variables $X_1,\ \ldots,\ X_p$ are random, not fixed. We may therefore, in this general case, use a Monte Carlo method to estimate stand biomass. The pseudo-algorithm of this Monte Carlo method is the same as that used previously `r ifelse(book_format == "latex", "(see p.\\pageref{psa})", "")`:

1. For $k$ from $1$ to $Q$, where $Q$ is the number of Monte Carlo iterations:
    + 1.1. for $i$ from 1 to $p$, draw $\hat{X}_i^{(k)}$ following a distribution corresponding to the variability of the stand sample (this distribution depends on the type of sampling conducted, the size and number of plots inventoried, etc.);
    + 1.2. draw a vector $\hat{\theta}^{(k)}$ following a multinormal distribution of mean $\hat{\theta}$ and variance-covariance matrix $\hat{\boldsymbol{\Sigma}}$;
    + 1.3. calculate the prediction $\hat{Y}^{(k)}=f(\hat{X}_1^{(k)},\ \ldots,\ \hat{X}_p^{(k)};\hat{\theta}^{(k)})$.
2. The confidence interval of the prediction is the empirical confidence interval of the $Q$ values $\hat{Y}^{(1)}$, \ldots,
$\hat{Y}^{(Q)}$.


