

# Conclusions and recommendations {-}

`r ifelse(book_format == "latex", "\\markboth{Conclusions and recommendations}{}", "")`

`r ifelse(book_format == "html" & with_watermark, "<div class='watermark'>DRAFT</div>", "")`

The methods used to estimate tree volume and biomass are constantly evolving as the search is always on for estimations that are as close as possible to reality. Volume and biomass estimation models have undergone different changes in different ecological areas. In dry tropical areas, the problem of obtaining sufficient supplies of firewood dates backs to ancient times, and here primarily allometric equations have been developed to quantify fuelwood. In wet tropical areas, where felling is mainly for timber, equations have been developed primarily to estimate volume. Today, climate change is of increasing concern and interest is being shown in biomass models in both wet and dry forests.

Biomass measurements are destined to increase in coming years to meet the needs of carbon stock estimations and understand the contribution made by terrestial ecosystems to the carbon cycle. Experience acquired in volume estimations has shown that two or three thousand observations are needed to estimate the trunk volume of *one* given species with sufficient precision to cover the variability across  the geographic range of its distribution [@ctft89]. By comparison, the biomass model established by @chave05, which is one of the most widely used biomass models today, was calibrated using 2410 observations. It is a pan-tropical model that covers all species and all ecological zones in dry and wet areas! The similarity between these two sample sizes --- despite variability that differs by several orders of magnitude --- shows that, with regard to biomass measurements, there is still considerable scope for progress in exploring the full extent of natural variability. And this particularly given that biomass, which involves all the compartments of a tree, probably has far greater intrinsic variability than simply the volume of the trunk.

The reliability of biomass estimations can be enhanced by increasing the number of observations available. But measuring the above-ground biomass of a tree requires a far greater effort than measuring the volume of its trunk. And the effort is even greater still when root biomass is included. At present, it is very unlikely that vast campaigns will be funded to measure the above-ground and below-ground biomass of trees. Like for @chave05, the construction of new allometric equations must therefore be based on compilations of datasets collected at different locations by independent teams. Standardized biomass measurement methods, and model-fitting statistics capable of including additional information through effect covariables are therefore crucial if we are to improve tree biomass estimations in the years ahead. Experiments on regular stands (effects of ontogeny, plantation density, soil fertility or fertilizers, and more generally the effects of silviculture) will facilitate the construction of these generic models.

Contrary to other guides already available, we sought here to cover the entire process of constructing allometric equations, from field to prediction, and including model fitting. But we do not claim to have covered all possible situations. Many cases will require the development of specific methods. Large trees with buttresses, for instance, pose special problems for any prediction of their biomass --- starting with the difficulty that their diameter at breast height, which is the first entry variable for most models, is not measurable. Hollow trees, strangler fig, bamboo and large epiphytes are all species with particularities that will pose problems when applying the methods put forward in this guide. New dendrometric methods will very likely have to be developed to tackle these specific cases. Tools such as 3D modeling, photogrammetry, radar and lasers, on the ground or in the air, will facilitate or revolutionize biomass estimation methods and perhaps ultimately replace the power saw and weighing scales.

Statistical methods are also evolving. A comparison of the report by @whraton87 with the fitting methods used today in forestry clearly shows just how much progress has been made in the use of increasingly cutting-edge statistical methods, and that we have attempted to explain in this guide. The consideration of within-stem variability could become common practice in the future when fitting biomass models.

Improvements in measurements and model fitting methods, and the increasing use of field measurements, will improve the processes of scientific research and tree biomass estimations only if the models and methods produced are made available in a transparent manner. A great deal of data are confined to libraries and are never published in scientific journals or on the Internet. Also, for a country that does not possess biomass data for some of its ecological areas, data obtained by neighboring countries or in identical ecological areas may not be easily accessible. We therefore encourage forestry players to identify the data already available for ecological areas or countries of interest. These data may be integrated into databases and serve to identify gaps. These gaps can then be plugged through field measurements conducted in accordance with the advice and red lines given in this guide.

If we are to guarantee continuity in the efforts made to improve estimations, a data archiving system will have to be set up as a starting point to improve future estimations. A robust archiving system should help reduce the efforts made by future workers to understand and recalculate current estimations. Also, it is important to underline that the methods set up must be consistent over time. This guide describes different measuring methods, but it is preferable to adopt one single method that can be easily reproduced and is less dependent upon financial, technological and human factors. Should an alternative method be developed for practical reasons, this should be reported and be made accessible such that the next guide will include the full diversity of the methodologies possible. Finally, it is always best to adopt methods that are both simple and reproducible.
