

# (APPENDIX) Appendix {-}


# List of red lines {-}

`r ifelse(book_format == "latex", "\\markboth{List of red lines}{}", "")`

1. \@ref(exr:read) (ref:read) <!-- ch. 4 -->

1. \@ref(exr:feBvD) (ref:feBvD)

1. \@ref(exr:feBvD2H) (ref:feBvD2H)

1. \@ref(exr:frho) (ref:frho)

1. \@ref(exr:feln) (ref:feln)

1. \@ref(exr:feln2) (ref:feln2) <!-- ch. 5 -->

1. \@ref(exr:rllnBvD) (ref:rllnBvD)

1. \@ref(exr:rllnBvD2H) (ref:rllnBvD2H)

1. \@ref(exr:flnDpol) (ref:flnDpol)

1. \@ref(exr:flnDlnH) (ref:flnDlnH)

1. \@ref(exr:frlpD2H) (ref:frlpD2H)

1. \@ref(exr:fDpara) (ref:fDpara)

1. \@ref(exr:fDD2var) (ref:fDD2var)

1. \@ref(exr:fH) (ref:fH)

1. \@ref(exr:fexpDpol) (ref:fexpDpol)

1. \@ref(exr:finvD) (ref:finvD) <!-- 6.1 -->

1. \@ref(exr:fnlsD) (ref:fnlsD)

1. \@ref(exr:fnlsD2H) (ref:fnlsD2H)

1. \@ref(exr:fnlsDH) (ref:fnlsDH)

1. \@ref(exr:fnlmD) (ref:fnlmD)

1. \@ref(exr:fnlmD2H) (ref:fnlmD2H)

1. \@ref(exr:fnlmDH) (ref:fnlmDH) <!-- 6.2 -->

1. \@ref(exr:selvar) (ref:selvar)

1. \@ref(exr:fboite) (ref:fboite)

1. \@ref(exr:fboite2) (ref:fboite2)

1. \@ref(exr:selB) (ref:selB)

1. \@ref(exr:sellnB) (ref:sellnB)

1. \@ref(exr:fmeth) (ref:fmeth) <!-- 6.3 -->

1. \@ref(exr:fmspe) (ref:fmspe)

1. \@ref(exr:fdens) (ref:fdens)

1. \@ref(exr:fidens) (ref:fidens) <!-- 6.4 -->

1. \@ref(exr:ficlnD) (ref:ficlnD)

1. \@ref(exr:ficlnDH) (ref:ficlnDH)

1. \@ref(exr:CFB) (ref:CFB)

1. \@ref(exr:smear) (ref:smear) <!-- ch. 7 -->
