

# Lexicon of mathematical symbols {-}

`r ifelse(book_format == "latex", "\\markboth{Lexicon of mathematical symbols}{}", "")`


## Latin symbols {-}

```{r}
latin <- rbind(
  c("$a$"            , "estimated value of a coefficient in a predictive model"), 
  c("$A$"            , "area of a sampling plot"),
  c("$\\mathcal{A}$"  , "area of a stand"),
  c("$b$"            , "estimated value of a coefficient in a predictive model"),
  c("$B$"            , "biomass of an aliquot, a compartment (trunk, branches, leaves $\\ldots$), of a tree or stand"),
  c("$\\mathrm{CV}_X$", "coefficient of variation of a variable $X$"),
  c("$c$"            , "exponent of a power expression"),
  c("$C$"            , "definition 1: circumference of a tree; definition 2: cost of sampling; definition 3: model validation criterion"),
  c("$D$"            , "diameter of a tree at breast height (dbh)"),
  c("$D_0$"          , "dbh of the dominant tree in a stand"),
  c("$E$"            , "precision of the estimation of a variable"),
  c("$f$"              , "a function linking a response variable to one or more effect variables"),
  c("$F$"            , "Furnival's index"),
  c("$g$"            , "a function"), 
  c("$G$"            , "basal area of a tree or a stand"),
  c("$h$"            , "a height between zero (the ground) and the height $H$ of the tree"),
  c("$H$"            , "height of a tree"),
  c("$H_0$"          , "height of the dominant tree in the stand"),
  c("$\\mathbf{I}_n$" , "Fisher's information matrix for a sample of size $n$"),
  c("$k$"            , "multiplier of a power expression"),
  c("$K$"            , "number of subsets in a cross validation"),
  c("$\\ell$"         , "likelihood of a sample"),
  c("$\\mathcal{L}$"   , "log-likelihood of a sample"),
  c("$L$"            , "length of a log"), 
  c("$M$"            , "definition 1: number of biomass compartments in a tree; definition 2: number of competitor models for predicting the same response variable"),
  c("$n$"            , "sample size"),
  c("$N$"            , "definition 1: total number of sampling units (tree or plot) in a stand; definition 2: stand density (number of stems per hectare)"),
  c("$\\mathcal{N}$"  , "the normal distribution (also called a Gaussian or Laplace-Gauss distribution)"),
  c("$p$"            , "number of effect variables in a model (not including the y-intercept)"),
  c("$P$", " stem profile (plot giving the area of a cross-cut through the trunk at different heights)"), 
  c("$q$", "definition 1: number of estimated parameters in a model; definition 2: quantile of the standard normal distribution"), 
  c("$Q$", "number of Monte Carlo iterations"), 
  c("$R$", "definition 1: a model's determination coefficient; definition 2 (in the model selection theory): a risk; definition 3: radius of a log"), 
  c("$S$", "number of strata in a stratification"), 
  c("$S_X$", "empirical standard deviation of a variable $X$"), 
  c("$\\mathcal{S}_n$", "dataset containing $n$ observations"), 
  c("$t_{n}$", "quantile of a Student's distribution with $n$ degrees of freedom"), 
  c("$T$", "age of a plantation"), 
  c("$V$", "volume of a log, tree or stand"), 
  c("$w$", "definition 1: weight of an observation in a weighted regression; definition 2: weight of a model in a mixture of models"), 
  c("$X$", "a variable (generally the effect variable of a model)"), 
  c("$\\mathbf{x}$", "a vector of effect variables"), 
  c("$\\mathbf{X}$", "design matrix for a linear model"), 
  c("$Y$", "a variable (generally the response variable of a model)"), 
  c("$\\mathbf{Y}$", "response vector of a multivariate model"), 
  c("$z$", "a latent variable for the EM algorithm"), 
  c("$Z$", "a variable (generally a covariable defining the stratification of a dataset)")
)

kab_latin <- tibble(sym = latin[,1], txt = latin[,2])

kab_opt <- list(
  x = kab_latin, 
  booktab = TRUE,
  escape = F,
  col.names = c("", ""), 
  align = "rl"
  )

if (book_format == "latex") {
  
  display_table() %>% 
    kableExtra::column_spec(column = 2, width = "10cm" )  %>%
    kableExtra::kable_styling(latex_options =c("repeat_header")) %>%
    sub("\\\\toprule", "", .) %>%
    sub("\\\\midrule", "", .) %>%
    sub("\\\\bottomrule", "", .)
  
} else if (book_format == "html") {
  
  display_table() %>%
    kableExtra::column_spec(column = 2, width = "20cm")
  
} else {
  
  display_table()
  
}


```


## Greek symbols {-}

```{r}
greek <- rbind(
  c("$\\alpha$"                   , 'definition 1: (unknown) "true" value of a coefficient in a predictive model; definition 2: confidence threshold for a confidence interval (generally 5\\ \\%)'), 
  c("$\\beta$"                    , "(unknown) ``true'' value of a coefficient in a predictive model"), 
  c("$\\gamma$"                   , "loss function (in the model selection theory)"), 
  c("$\\delta$"                   , "Dirac's function"), 
  c("$\\Delta$"                   , "a difference in value for a given variable"), 
  c("$\\varepsilon$"              , "residual error of a predictive model"), 
  c("$\\boldsymbol{\\varepsilon}$", "vector of the residual errors of a multivariate model"), 
  c("$\\zeta$"                    , "residual covariance between two compartments"), 
  c("$\\eta$"                     , "volumetric shrinkage coefficient"), 
  c("$\\theta$"                   , "a set of model parameters"), 
  c("$\\boldsymbol{\\theta}$"     , "a vector of parameters in a multivariate model"), 
  c("$\\vartheta$"                , "a set of parameters"), 
  c("$\\mu$"                      , 'expectation of a random variable = (unknown) "true" mean of a variable to be estimated'), 
  c("$\\xi$"                      , "Box-Cox transformation parameter"), 
  c("$\\rho$"                     , "wood density"), 
  c("$\\sigma$"                   , "standard deviation of the residual error of a predictive model"), 
  c("$\\boldsymbol{\\Sigma}$"     , "variance-covariance matrix of a multinormal distribution"), 
  c("$\\tau$"                     , "(unknown) ``true'' standard deviation of a variable to be estimated "), 
  c("$\\phi$"                     , "probability density of a normal distribution"), 
  c("$\\psi$"                     , "function defining a variable transformation"), 
  c("$\\chi$"                     , "water content"), 
  c("$\\chi_0$"                   , "fiber saturation point"), 
  c("$\\omega$"                   , "a proportion (for example, the proportion of fresh biomass in a log)")
)
  
kab_greek <- tibble(sym = greek[,1], txt = greek[,2])

kab_opt <- list(
  x = kab_greek, 
  booktab = TRUE,
  escape = F,
  col.names = c("", ""), 
  align = "rl"
  )

if (book_format == "latex") {
  
  display_table() %>% 
    kableExtra::column_spec(column = 2, width = "10cm" )  %>%
    kableExtra::kable_styling(latex_options =c("repeat_header")) %>%
    sub("\\\\toprule", "", .) %>%
    sub("\\\\midrule", "", .) %>%
    sub("\\\\bottomrule", "", .)
  
} else if (book_format == "html") {
  
  display_table() %>%
    kableExtra::column_spec(column = 2, width = "20cm")
  
} else {
  
  display_table()
  
}
```


## Non-alphabetical symbols {-}


```{r}
nalpha <- rbind(
  c("$\\varnothing$", 'diameter of a tree, a log, a branch or a root')
)
  
kab_nalpha <- tibble(sym = nalpha[,1], txt = nalpha[,2])

kab_opt <- list(
  x = kab_nalpha, 
  booktab = TRUE,
  escape = F,
  col.names = c("", ""), 
  align = "rl"
  )

if (book_format == "latex") {
  
  display_table() %>% 
    kableExtra::column_spec(column = 2, width = "10cm" )  %>%
    kableExtra::kable_styling(latex_options =c("repeat_header")) %>%
    sub("\\\\toprule", "", .) %>%
    sub("\\\\midrule", "", .) %>%
    sub("\\\\bottomrule", "", .)
  
} else if (book_format == "html") {
  
  display_table() %>%
    kableExtra::column_spec(column = 2, width = "20cm")
  
} else {
  
  display_table()
  
}
```

