

In the case of multispecific datasets, the species is a stratification covariable that warrants special attention. If the dataset includes only a few species (less than about 10), and there are sufficient observations per species (see \S\ \ref{size}), then species may be considered to be a stratification covariable like any other. The model in this case would be divided into $S$ specific models, or the models could be grouped together based on the allometric resemblance of the species.

If the dataset contains many species, or if only a few observations are available for certain species, it is difficult to treat the species as a stratification covariable. A solution in this case consists in using species *functional traits*. Functional traits are defined here, a little abusively, as the numerical variables that characterize the species [@diaz97; @rosch97; @lavorel02; see \citealp{violle07} for a more rigorous definition]. The most widely used trait in biomass models is wood density. If we decide to use functional traits to represent species, these traits intervene as effect variables in the model in the same way as the effect variables that characterize the tree, for example its dbh or height. The single-entry (dbh) monospecific biomass model of the power type, which in its linear form may be written:
\[
\ln(B)=a_0+a_1\ln(D)+\varepsilon
\]
will thus, in the multispecific case, become a double-entry biomass model:
\[
\ln(B)=a_0+a_1\ln(D)+a_2\ln(\rho)+\varepsilon
\]
if we decide to use wood density $\rho$ to represent the specific effect.

\begin{filrouge}{Specific wood density-dependent biomass model}{fdens}%
In red line \@ref(exr:fmspe), species-related information was taken into account in the model $\ln(B)=a+b\ln(D^2H)$ through a qualitative covariable. We can now capture this information through specific wood density $\rho$. The fitted model is therefore:
\begin{equation}
\ln(B)=a_0+a_1\ln(D^2H)+a_2\ln(\rho)+\varepsilon(\#eq:dens)
\end{equation}
where
\[
\mathrm{Var}(\varepsilon)=\sigma^2
\]
As wood density in the dataset was measured for each individual, we must start by calculating mean wood density for each species:
\R{dm <- tapply(dat\$dens,dat\$species,mean)%
\\ dat <- cbind(dat,dmoy=dm[as.character(dat\$species)])}%
The `dat` dataset now contains an additional variable `dmoy` that gives specific wood density. The model is fitted by the command:
\R{m <- lm(log(Btot)$\sim$I(log(dbh\^{}2*heig))+I(log(dmoy)),data=dat[dat\$Btot>0,])%
\\ summary(m)}%
which yields:
\Rout{\begin{tabular}{lrrrrl}%
                      & Estimate & Std. Error & t value & Pr(>|t|) &    \\ %
(Intercept)           & -8.38900 &    0.26452 & -31.714 &  < 2e-16 & ***\\ %
I(log(dbh\^{}2*heig)) &  0.85715 &    0.02031 &  42.205 &  < 2e-16 & ***\\ %
I(log(dmoy))          &  0.72864 &    0.17720 &   4.112 & 0.000202 & ***\\ %
\end{tabular}}%
with a residual standard deviation of \decimal{0}{3442} and $R^2=\decimal{0}{9806}$. The model is therefore written:
$\ln(B)=-\decimal{8}{38900}+\decimal{0}{85715}\ln(D^2H)+\decimal{0}{72864}\ln(\rho)$.
Is it better to take account of the species through wood density, as we have just done, or by constructing specific models as in red line \@ref(exr:fmspe)? To answer this question we need to compare model (\ref{mspe}) to the model (\ref{dens}) using the AIC:
\R{AIC(m)}%
which yields $\mathrm{AIC}=\decimal{34}{17859}$ for specific model (\ref{mspe}) and $\mathrm{AIC}=\decimal{33}{78733}$ for the model (\ref{dens}) that uses wood density. The latter therefore is slightly better, but the difference in AIC is nevertheless minor.
\end{filrouge}

To better take account of wood density variations within a tree, it is possible to analyze inter- and intra-specific variations rather than use a mean density based on the hypothesis that wood density is the same from the pith to the bark and from the top to the bottom of trees (see chapter \@ref(biol)). Wood density can be modeled by taking account of factors such as species, functional group, tree dimensions, and radial or vertical position in the tree. An initial comparison may be made using Friedman's analysis of variance test, followed by Tuckey's highly significant difference (HSD) test. These tests will indicate the variables that most influence wood density. This wood density may then be modeled based on these variables [@henry10].

\begin{filrouge}{Individual wood density-dependent biomass model}{fidens}%
In red line \@ref(exr:fdens), wood density $\rho$ was defined for the species by calculating the mean of individual densities for trees in the same species. Let us now fit a biomass model based on individual wood density measurements in order to take account of inter-individual variations in wood density in a given species. The fitted model is:
\[
\ln(B)=a_0+a_1\ln(D)+a_2\ln(\rho)+\varepsilon
\]
where
\[
\mathrm{Var}(\varepsilon)=\sigma^2
\]
where $\rho$ unlike in red line \@ref(exr:fdens), is here the *individual* measurement of wood density. The model is fitted by the command:
\R{m <- lm(log(Btot)$\sim$I(log(dbh))+I(log(dens)),data=dat[dat\$Btot>0,])%
\\ summary(m)}%
which yields:
\Rout{\begin{tabular}{lrrrrl}%
             & Estimate & Std. Error & t value & Pr(>|t|) &    \\ %
(Intercept)  & -7.76644 &    0.20618 & -37.668 &  < 2e-16 & ***\\ %
I(log(dbh))  &  2.35272 &    0.04812 &  48.889 &  < 2e-16 & ***\\ %
I(log(dens)) &  1.00717 &    0.14053 &   7.167 & 1.46e-08 & ***\\ %
\end{tabular}}%
with a residual standard deviation of \decimal{0}{3052} and $R^2=\decimal{0}{9848}$. The model is written:
$\ln(B)=-\decimal{7}{76644}+\decimal{2}{35272}\ln(D)+\decimal{1}{00717}\ln(\rho)$.
According to this model, biomass is dependent upon individual wood density by the term $\rho^{1.00717}$, i.e. practically $\rho$. By way of a comparison, model (\ref{dens}) was dependent upon specific wood density by the term $\rho^{0.72864}$. From a biological standpoint, the exponent 1.00717 is more satisfactory than the exponent 0.72864 since it means that the biomass is the product of a volume (that depends solely on tree dimensions) and a density. The difference between the two exponents may be attributed to inter-individual variations in wood density within the species. But the model based on individual wood density has little practical usefulness as it would require a wood density measurement in every tree whose biomass we are seeking to predict.
\end{filrouge}

\subsection{Tree compartments\label{cmpt}}

Tree biomass is determined separately for each compartment in the tree (stump, trunk, large branches, small branches, leaves, etc.). Total above-ground biomass is the sum of these compartments. The approach already presented for fitting a model could be followed for each compartment separately. In this case we would construct a model for leaf biomass, a model for the biomass of the large branches, etc.. This approach integrates dataset stratification. Thus, we could initially fit a model for each compartment and each stratum; as a second step, and depending on the differences found between strata, we could aggregate the strata and/or parameterize the model in order to construct a model by compartment for all the strata. But the approach would not end there. We could also continue the data integration in order to move toward a smaller number of more integrating models.

#### Compartment additivity

As total above-ground biomass is the sum of the biomasses of the different compartments, it could be imagined that the best model for predicting above-ground biomass is the sum of the models predicting the biomass of each compartment. In fact, because of the correlations between the biomasses of the different compartment, this is not the case [@cunia84; @cunia85b; @parresol99]. Also, certain model families are not stable by addition. This in particular is the case for power models: the sum of two power functions is not a power function. If we have fitted a power model for each compartment:
\begin{eqnarray*}
B^{\mathrm{stump}} &=& a_1D^{b_1}
\\ B^{\mathrm{trunk}} &=& a_2D^{b_2}
\\ B^{\mathrm{large\ branches}} &=& a_3D^{b_3}
\\ B^{\mathrm{small\ branches}} &=& a_4D^{b_4}
\\ B^{\mathrm{leaves}} &=& a_5D^{b_5}
\end{eqnarray*}
The sum $B^{\mbox{\scriptsize above-ground}}=B^{\mathrm{stump}}
+B^{\mathrm{trunk}}+B^{\mathrm{large\ branches}}
+B^{\mathrm{small\ branches}}+B^{\mathrm{leaves}}$ =
$\sum_{m=1}^5a_m$ $D^{b_m}$ is not a power function of dbh. By contrast, polynomial models are stable by addition.

#### Fitting a multivariate model

In order to take account of the correlations between the biomasses of the different compartments, we can fit the models relative to the different compartments in a simultaneous manner rather than separately. This last step in model integration requires us to redefine the response variable. As we are looking to predict simultaneously the biomasses of different compartments, we are no longer dealing with a response variable but a *response vector* $\vect{Y}$. The length of this vector is equal to the number $M$ of compartments. For example, if the response variable is the biomass,
\[
\vect{Y}=\left[
\begin{array}{l}
B^{\mbox{\scriptsize above-ground}}\\ %
B^{\mathrm{stump}}\\ %
B^{\mathrm{trunk}}\\ %
B^{\mathrm{large\ branches}}\\ %
B^{\mathrm{small\ branches}}\\ %
B^{\mathrm{leaves}}
\end{array}
\right]
\]
If the response variable is the log of the biomass,
\[
\vect{Y}=\left[
\begin{array}{l}
\ln(B^{\mbox{\scriptsize above-ground}})\\ %
\ln(B^{\mathrm{stump}})\\ %
\ln(B^{\mathrm{trunk}})\\ %
\ln(B^{\mathrm{large\ branches}})\\ %
\ln(B^{\mathrm{small\ branches}})\\ %
\ln(B^{\mathrm{leaves}})
\end{array}
\right]
\]
Let $Y_m$ be the response variable of the $m$th compartment
(where $m=1$, \ldots, $M$). Without loss of generality, we can consider that all the compartments have the same set $X_1$, $X_2$, \ldots, $X_p$ of effect variables (if a variable is not included in the prediction of a compartment, the corresponding coefficient can simply be set at zero). A model that predicts a response vector rather than a response variable is a multivariate model. An observation used to fit a multivariate model consists of a vector ($Y_1$, \ldots, $Y_M$, $X_1$, \ldots, $X_p$) of length $M+p$. The residual of a multivariate model is a vector $\boldsymbol{\varepsilon}$ of length $M$, equal to the difference between the observed response vector and the predicted response vector.

The expression of an $M$-variate model differs from the $M$ univariate models corresponding to the different compartments only by the structure of the residual error; the structure of the mean model does not change. Let us consider the general case of a non-linear model. If the $M$ univariate models are:
\begin{equation}
Y_m=f_m(X_1,\ \ldots,\ X_p;\theta_m)+\varepsilon_m(\#eq:uvar)
\end{equation}
for $m=1$, \ldots, $M$, then the multivariate model is written:
\[
\vect{Y}=\vect{F}(X_1,\ \ldots,\ X_p;\boldsymbol{\theta})+
\boldsymbol{\varepsilon}
\]
where $\vect{Y}=\tr{[Y_1,\ \ldots,\ Y_M]}$,
$\boldsymbol{\theta}=\tr{[\theta_1,\ \ldots,\ \theta_M]}$, and
\begin{equation}
\vect{F}(X_1,\ \ldots,\ X_p;\boldsymbol{\theta})=\left[
\begin{array}{c}
f_1(X_1,\ \ldots,\ X_p;\theta_1)
\\\vdots\\
f_m(X_1,\ \ldots,\ X_p;\theta_m)
\\\vdots\\
f_M(X_1,\ \ldots,\ X_p;\theta_M)
\end{array}
\right](\#eq:mvar)
\end{equation}
The residual vector $\boldsymbol{\varepsilon}$ now follows a centered multinormal distribution, with a variance-covariance matrix of:
\[
\mathrm{Var}(\boldsymbol{\varepsilon})\equiv\boldsymbol{\Sigma}
=\left[
\begin{array}{cccc}
\sigma_1^2 & \zeta_{12} & \cdots        & \zeta_{1M}\\ %
\zeta_{21} & \sigma_2^2 & \ddots        & \vdots\\ %
\vdots     & \ddots     & \ddots        & \zeta_{M-1,M}\\ %
\zeta_{M1} & \cdots     & \zeta_{M,M-1} & \sigma_M^2
\end{array}
\right]
\]
Matrix $\boldsymbol{\Sigma}$ is symmetrical with $M$ lines and $M$ columns, such that $\sigma_m^2=\mathrm{Var}(\varepsilon_m)$ is the residual variance of the biomass of the $m$th compartment and $\zeta_{ml}=\zeta_{lm}$ is the residual covariance between the biomass of the $m$th compartment and that of the $l$th compartment. Like in the univariate case, two residuals corresponding to two different observations are assumed to be independent: $\boldsymbol{\varepsilon}_i$ is independent of $\boldsymbol{\varepsilon}_j$ pour $i\neq j$. The difference arises from the fact that the different compartments are no longer assumed to be independent one from another.

A multivariate model such as (\ref{mvar}) is fitted based on the same principles as univariate models (\ref{uvar}). If the variance-covariance matrix $\boldsymbol{\Sigma}$ is diagonal (i.e. $\zeta_{ml}=0$, $\forall m$, $l$), then the fitting of the multivariate model (\ref{mvar}) is equivalent to the separate fitting of the $M$ univariate models (\ref{uvar}). In the case of a linear model, estimated values for coefficients $\theta_1$, $\theta_2$, \ldots, $\theta_M$ resulting from fitting the $M$-variate linear model are the same as the values obtained by the separate fitting of the $M$ univariate linear models (on condition that the same effect variables $X_1$, \ldots, $X_p$ are used in all cases) \citep[chapter 3]{muller06}. But the significance tests associated with the coefficients do not give the same results in the two cases. If the different compartments are sufficiently correlated one with the other, the simultaneous fitting of all the compartments by the multivariate model (\ref{mvar}) will yield a more precise estimation of model coefficients, and therefore more precise biomass predictions.

#### Harmonizing a model

In certain cases, particularly energy wood, we are looking to predict the dry biomass of the trunk at different cross-cut diameters. For instance, we want to predict simultaneously the total biomass $B$ of the trunk, the biomass $B_{7}$ of the trunk to the small-end diameter of 7~cm, and the biomass $B_{10}$ of the trunk to the small-end diameter of 10~cm. We could consider the entire trunk, the trunk to a cross-cut of 7~cm, and the trunk to a cross-cut of 10~cm as three different compartments and apply the same fitting principles as presented in the previous section. In fact, the problem is more complex because, unlike the trunk and leaf compartments which are separate, the compartments defined by different cross-cut diameters are nested one within the others: $B=B_{7}+$ biomass of the section to a small-end diameter of 7~cm, and $B_{7}=B_{10}+$ biomass of the section from the 10~cm to the 7~cm small-end cross-cuts. Thus, the multivariate model that predicts vector ($B$, $B_7$, $B_{10}$) must ensure that $B>B_{7}>B_{10}$ across the entire valid range of the model. The process consisting of constraining the multivariate model in such a manner that it predicts the biomasses of the different compartments while checking the logic of their nesting is called model *harmonization* [@parresol99]. @jacobs80 and @cunia85 have put forward solutions to this problem in the form of equations relating the coefficients in the models used for the different compartments. In this case we must fit an $M$-variate model (if there are $M$ cross-cut diameters) while ensuring that the coefficients $\theta_1$, \ldots, $\theta_M$ corresponding to the $M$ cross-cut diameters satisfy a number of equations linking them together. When the coefficients in the multivariate model are estimated by maximum likelihood, their numerical estimation is in fact a problem of constrained optimization.

If predicting the volume or biomass of a stem, an alternative to the volume or biomass model is to use stem profile integration [@parresol89; @parresol99]. Let $P(h)$ be a stem profile, i.e. a plot of trunk transversal section area against height $h$ from the ground ($h$ also represents the length when a stem is followed from its large to its small end) [@maguire96; @dean06; @metcalf09]. If the section through the stem is roughly circular, the diameter of the tree at height $h$ may be calculated as: $D(h)=\sqrt{4P(h)/\pi}$. The biomass of the trunk to a cross-cut diameter $D$ is calculated by integrating the stem profile from the ground ($h=0$) to height $P^{-1}(\frac{\pi}{4}D^2)$ corresponds to this diameter:
\[
B_D=\int_0^{P^{-1}(\frac{\pi}{4}D^2)}\rho(h)\;P(h)\ \mathrm{d}h
\]
where $\rho(h)$ is wood density at height $h$. Stem volume to cross-cut diameter $D$ is calculated in the same manner, except that $\rho$ is replaced by 1. The stem profile approach has the advantage that model harmonization here is automatic. But it is an approach that is conceptually different from volume and biomass models, with specific fitting problems [@fang99; @parresol99], and is outside the scope of this guide. It should be noted that when dealing with very large trees, for which it is almost impossible to measure biomass directly, the stem profile approach is a relevant alternative [@vanpelt01; @dean03; @dean03b; @dean06; @sillett10].

